openapi: "3.0.0"
info:
  title: "Deployka Documentation"
  version: "1.0.0"
  description: "API documentation for deployka"
  contact:
    name: "nKeys Kuo"
    email: "nkeyskuo124@example.com"
paths:
  /users:
    get:
      summary: "Retrieve a list of users"
      description: "Retrieve a list of users from the database."
      responses:
        '200':
          description: "A list of users."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: "The user ID."
                      example: 1
                    name:
                      type: string
                      description: "The user's name."
                      example: "John Doe"
